In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("usedCars.csv")

In [4]:
data.isnull().sum()

Id                     0
Company                0
Model                  0
Variant                0
FuelType               1
Colour                 0
Kilometer              0
BodyStyle              0
TransmissionType     714
ManufactureDate        0
ModelYear              0
CngKit              1042
Price                  0
Owner                  0
DealerState            0
DealerName             0
City                   0
Warranty               0
QualityScore           0
dtype: int64

In [5]:
transmission_mode=data['TransmissionType'].mode()

In [6]:
transmission_mode=transmission_mode[0]

In [7]:
data['TransmissionType']=data['TransmissionType'].fillna(transmission_mode)

In [8]:
data.isnull().sum()

Id                     0
Company                0
Model                  0
Variant                0
FuelType               1
Colour                 0
Kilometer              0
BodyStyle              0
TransmissionType       0
ManufactureDate        0
ModelYear              0
CngKit              1042
Price                  0
Owner                  0
DealerState            0
DealerName             0
City                   0
Warranty               0
QualityScore           0
dtype: int64

In [9]:
fuel_mode=np.array(data['FuelType'].mode())

In [10]:
fuel_mode=fuel_mode[0]

In [11]:
type(fuel_mode)

str

In [12]:
data['FuelType'] = data['FuelType'].fillna(fuel_mode)

In [13]:
data

,Id,Company,Model,Variant,FuelType,Colour,Kilometer,BodyStyle,TransmissionType,ManufactureDate,ModelYear,CngKit,Price,Owner,DealerState,DealerName,City,Warranty,QualityScore
0,555675,MARUTI SUZUKI,CELERIO(2017-2019),1.0 ZXI AMT O,PETROL,Silver,33197,HATCHBACK,Manual,2018-02-01,2018,NaN,5.75 Lakhs,1st Owner,Karnataka,Top Gear Cars,Bangalore,1,7.8
1,556383,MARUTI SUZUKI,ALTO,LXI,PETROL,Red,10322,HATCHBACK,Manual,2021-03-01,2021,NaN,4.35 Lakhs,1st Owner,Karnataka,Renew 4 u Automobiles PVT Ltd,Bangalore,1,8.3
2,556422,HYUNDAI,GRAND I10,1.2 KAPPA ASTA,PETROL,Grey,37889,HATCHBACK,Manual,2015-03-01,2015,NaN,4.7 Lakhs,1st Owner,Karnataka,Anant Cars Auto Pvt Ltd,Bangalore,1,7.9
3,556771,TATA,NEXON,XT PLUS,PETROL,A Blue,13106,HATCHBACK,Manual,2020-08-01,2020,NaN,9.9 Lakhs,1st Owner,Karnataka,Adeep Motors,Bangalore,1,8.1
4,559619,FORD,FIGO,EXI DURATORQ 1.4,DIESEL,Silver,104614,HATCHBACK,Manual,2010-11-01,2010,NaN,2.7 Lakhs,2nd Owner,Karnataka,Zippy Automart,Bangalore,0,7.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059,588906,HYUNDAI,ELITE I20(2020-2020),ASTA O 1.2 BS VI,PETROL,White,42918,HATCHBACK,Manual,2020-09-01,2020,NaN,7.15 Lakhs,1st Owner,Rajasthan,K.S. Motors,Jaipur,1,8.3
1060,588945,HYUNDAI,XCENT(2017-2020),S,PETROL,White,78910,SEDAN,Manual,2019-01-01,2019,NaN,5.00 Lakhs,1st Owner,Rajasthan,Rajasthan Car World,Jaipur,0,7.8
1061,588946,MAHINDRA,SCORPIO(2009-2014),VLX 2WD BS-III,DIESEL,White,76000,SUV,Manual,2013-05-01,2013,NaN,5.75 Lakhs,1st Owner,Rajasthan,Rajasthan Car World,Jaipur,0,6.8
1062,588949,MARUTI SUZUKI,VITARA BREZZA,VDI,DIESEL,Silver,80120,HATCHBACK,Manual,2018-06-01,2018,NaN,7.71 Lakhs,1st Owner,Rajasthan,Rajasthan Car World,Jaipur,0,7.4
1063,588950,HONDA,CITY,SV MT DIESEL,DIESEL,Urban Titanium,77500,SEDAN,Manual,2014-01-01,2014,NaN,4.99 Lakhs,2nd Owner,Rajasthan,Rajasthan Car World,Jaipur,0,6.8

In [14]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1064 entries, 0 to 1063
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                1064 non-null   int64
 1   Company           1064 non-null   str
 2   Model             1064 non-null   str
 3   Variant           1064 non-null   str
 4   FuelType          1064 non-null   str
 5   Colour            1064 non-null   str
 6   Kilometer         1064 non-null   int64
 7   BodyStyle         1064 non-null   str
 8   TransmissionType  1064 non-null   str
 9   ManufactureDate   1064 non-null   str
 10  ModelYear         1064 non-null   int64
 11  CngKit            22 non-null     str
 12  Price             1064 non-null   str
 13  Owner             1064 non-null   str
 14  DealerState       1064 non-null   str
 15  DealerName        1064 non-null   str
 16  City              1064 non-null   str
 17  Warranty          1064 non-null   int64
 18  QualityScore      1064 non-null   float64
dtypes: float64(1), int64(4), str(14)
memory usage: 158.1 KB

In [15]:
data.describe(include='all')

,Id,Company,Model,Variant,FuelType,Colour,Kilometer,BodyStyle,TransmissionType,ManufactureDate,ModelYear,CngKit,Price,Owner,DealerState,DealerName,City,Warranty,QualityScore
count,1064.000000,1064,1064,1064,1064,1064,1064.000000,1064,1064,1064,1064.000000,22,1064,1064,1064,1064,1064,1064.000000,1064.000000
unique,NaN,23,218,575,5,76,NaN,10,9,162,NaN,2,367,4,10,57,11,NaN,NaN
top,NaN,MARUTI SUZUKI,SWIFT,VXI,PETROL,White,NaN,HATCHBACK,Manual,2018-01-01,NaN,Company Fitted,6.25 Lakhs,1st Owner,Delhi,Car Choice Exclusif,Delhi,NaN,NaN
freq,NaN,252,38,37,671,289,NaN,423,983,25,NaN,14,22,897,196,67,196,NaN,NaN
mean,568156.542293,NaN,NaN,NaN,NaN,NaN,52807.187970,NaN,NaN,NaN,2016.864662,NaN,NaN,NaN,NaN,NaN,NaN,0.738722,7.770207
std,16438.139974,NaN,NaN,NaN,NaN,NaN,33840.296979,NaN,NaN,NaN,2.996786,NaN,NaN,NaN,NaN,NaN,NaN,0.439538,0.719717
min,525978.000000,NaN,NaN,NaN,NaN,NaN,101.000000,NaN,NaN,NaN,2003.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
25%,555321.500000,NaN,NaN,NaN,NaN,NaN,32113.500000,NaN,NaN,NaN,2015.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,7.500000
50%,572753.000000,NaN,NaN,NaN,NaN,NaN,49432.000000,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,7.800000
75%,583072.750000,NaN,NaN,NaN,NaN,NaN,68828.500000,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,8.100000
max,589122.000000,NaN,NaN,NaN,NaN,NaN,640000.000000,NaN,NaN,NaN,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,9.400000

In [16]:
data.columns = data.columns.str.lower()

In [17]:
data.head()

,id,company,model,variant,fueltype,colour,kilometer,bodystyle,transmissiontype,manufacturedate,modelyear,cngkit,price,owner,dealerstate,dealername,city,warranty,qualityscore
0,555675,MARUTI SUZUKI,CELERIO(2017-2019),1.0 ZXI AMT O,PETROL,Silver,33197,HATCHBACK,Manual,2018-02-01,2018,NaN,5.75 Lakhs,1st Owner,Karnataka,Top Gear Cars,Bangalore,1,7.8
1,556383,MARUTI SUZUKI,ALTO,LXI,PETROL,Red,10322,HATCHBACK,Manual,2021-03-01,2021,NaN,4.35 Lakhs,1st Owner,Karnataka,Renew 4 u Automobiles PVT Ltd,Bangalore,1,8.3
2,556422,HYUNDAI,GRAND I10,1.2 KAPPA ASTA,PETROL,Grey,37889,HATCHBACK,Manual,2015-03-01,2015,NaN,4.7 Lakhs,1st Owner,Karnataka,Anant Cars Auto Pvt Ltd,Bangalore,1,7.9
3,556771,TATA,NEXON,XT PLUS,PETROL,A Blue,13106,HATCHBACK,Manual,2020-08-01,2020,NaN,9.9 Lakhs,1st Owner,Karnataka,Adeep Motors,Bangalore,1,8.1
4,559619,FORD,FIGO,EXI DURATORQ 1.4,DIESEL,Silver,104614,HATCHBACK,Manual,2010-11-01,2010,NaN,2.7 Lakhs,2nd Owner,Karnataka,Zippy Automart,Bangalore,0,7.5

In [18]:
data['cngkit']=data['cngkit'].fillna('Not included')

In [19]:
pip install mysql-connector-python sqlalchemy pymysql

Requirement already satisfied: mysql-connector-python in .\.venv\Lib\site-packages (9.7.0)
Requirement already satisfied: sqlalchemy in .\.venv\Lib\site-packages (2.0.49)
Requirement already satisfied: pymysql in .\.venv\Lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in .\.venv\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in .\.venv\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
data['price']=data['price'].str.strip('Lakhs')

In [21]:
data['price']=data['price'].replace('95,000','0.95')

In [22]:
data['price']=data['price'].astype(float)

In [23]:
data['price']=data['price'].apply(lambda x:x*100000)

In [24]:
data

,id,company,model,variant,fueltype,colour,kilometer,bodystyle,transmissiontype,manufacturedate,modelyear,cngkit,price,owner,dealerstate,dealername,city,warranty,qualityscore
0,555675,MARUTI SUZUKI,CELERIO(2017-2019),1.0 ZXI AMT O,PETROL,Silver,33197,HATCHBACK,Manual,2018-02-01,2018,Not included,575000.0,1st Owner,Karnataka,Top Gear Cars,Bangalore,1,7.8
1,556383,MARUTI SUZUKI,ALTO,LXI,PETROL,Red,10322,HATCHBACK,Manual,2021-03-01,2021,Not included,435000.0,1st Owner,Karnataka,Renew 4 u Automobiles PVT Ltd,Bangalore,1,8.3
2,556422,HYUNDAI,GRAND I10,1.2 KAPPA ASTA,PETROL,Grey,37889,HATCHBACK,Manual,2015-03-01,2015,Not included,470000.0,1st Owner,Karnataka,Anant Cars Auto Pvt Ltd,Bangalore,1,7.9
3,556771,TATA,NEXON,XT PLUS,PETROL,A Blue,13106,HATCHBACK,Manual,2020-08-01,2020,Not included,990000.0,1st Owner,Karnataka,Adeep Motors,Bangalore,1,8.1
4,559619,FORD,FIGO,EXI DURATORQ 1.4,DIESEL,Silver,104614,HATCHBACK,Manual,2010-11-01,2010,Not included,270000.0,2nd Owner,Karnataka,Zippy Automart,Bangalore,0,7.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059,588906,HYUNDAI,ELITE I20(2020-2020),ASTA O 1.2 BS VI,PETROL,White,42918,HATCHBACK,Manual,2020-09-01,2020,Not included,715000.0,1st Owner,Rajasthan,K.S. Motors,Jaipur,1,8.3
1060,588945,HYUNDAI,XCENT(2017-2020),S,PETROL,White,78910,SEDAN,Manual,2019-01-01,2019,Not included,500000.0,1st Owner,Rajasthan,Rajasthan Car World,Jaipur,0,7.8
1061,588946,MAHINDRA,SCORPIO(2009-2014),VLX 2WD BS-III,DIESEL,White,76000,SUV,Manual,2013-05-01,2013,Not included,575000.0,1st Owner,Rajasthan,Rajasthan Car World,Jaipur,0,6.8
1062,588949,MARUTI SUZUKI,VITARA BREZZA,VDI,DIESEL,Silver,80120,HATCHBACK,Manual,2018-06-01,2018,Not included,771000.0,1st Owner,Rajasthan,Rajasthan Car World,Jaipur,0,7.4
1063,588950,HONDA,CITY,SV MT DIESEL,DIESEL,Urban Titanium,77500,SEDAN,Manual,2014-01-01,2014,Not included,499000.0,2nd Owner,Rajasthan,Rajasthan Car World,Jaipur,0,6.8

In [25]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:


engine = create_engine(
    "mysql+pymysql://root:"YOURPASSSHOULDBEHERE"@localhost/used_cars"
)

engine.connect()

In [27]:
data.to_sql(
    name='used_cars',
    con=engine,
    if_exists='replace',
    index=False
)

1064